### ISSUE TITLE
Change lock screen background color

### ISSUE THREAD

**Issue by jgeerds** [enricocid/Simply-Solid#2]
It seems like it is not possible to change the background color of the lock screen. The only way I know to change it is with the stock Android gallery app. But this works only for "real" pictures that are visible in the gallery app.

Would it be possible to implement this feature?

As a simple workaround it would be great to have an "export" option inside SimplySolid. Then you could use the normal gallery app to change to color.

**Comment by enricocid** [comment]
In cyanogenmod i use "no wallpaper" option to have the same wallpaper of the home...
I think I can add an option to save wallpapers to storage
I Will work on it during the week-end:)

**Comment by enricocid** [comment]
In cyanogenmod i use "no wallpaper" option to have the same wallpaper of the home...
I think I can add an option to save wallpapers to storage
I Will work on it during the week-end:)

**Comment by jgeerds** [comment]
I think this option is only available on Cyanogenmod but not stock Android (or CopperheadOS in my case)

**Comment by enricocid** [comment]
In Api 24 (android 7)Google added a new method and flags to WallpaperManager to apply wallpaper also to the Lockscreen
Below Api 24 i must search for something :) (Sorry, I have a redmi3 with cm13, didn't realize that such a thing could happen, gonna bring back my old N5 to life)

**Comment by enricocid** [comment]
@jgeerds  I added a fab button to save images to storage. Hope it is ok :)

**Comment by jgeerds** [comment]
I tested the new version via F-Droid and it works. Thanks a lot!

**Comment by CrimsonFork** [comment]
I've shortly noticed that VLC has the ability to change the image, at least temporary (Stock Android 5.0.1).

**Comment by enricocid** [comment]
VLC? What is? :)

**Comment by CrimsonFork** [comment]
Oh, it's just the greatest Open Source video player, avalible on every computer and modern mobile platform. Sadly, the F-Droid version is not the latest but I use that one anyway.

[Official site](https://www.videolan.org/)

[Android page](https://www.videolan.org/vlc/download-android.html)

[Source code](https://code.videolan.org/videolan/vlc-android)

There is a setting called "Media cover on lockscreen" which loads thumbmails from music files if avalible.

I hope that helps.

**Comment by enricocid** [comment]
Thank You:)

**Comment by enricocid** [comment]
https://github.com/enricocid/Simply-Solid/commit/ffa7601eaddc35f25926de313f41266088cf35ab

This will work for android versions >=Nougat
